name: Build and push main docker images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Build the interface
      run: npm run build
      env:
        DEVELOPMENT_BUILD: ${{ github.sha }}
    - name: Set version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
 
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Login to Aliyun
      uses: docker/login-action@v2
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
    
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.HUB_DOCKER_USERNAME }}
        password: ${{ secrets.HUB_DOCKER_PASSWORD }}
        
    - name: Build and push Beta Alpine Version
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.HUB_DOCKER_USERNAME }}/docker-registry-ui:${{ steps.vars.outputs.tag }}
          ${{ secrets.HUB_DOCKER_USERNAME }}/docker-registry-ui:latest
          registry.cn-hangzhou.aliyuncs.com/${{ secrets.HUB_DOCKER_USERNAME }}/docker-registry-ui:${{ steps.vars.outputs.tag }}
          registry.cn-hangzhou.aliyuncs.com/${{ secrets.HUB_DOCKER_USERNAME }}/docker-registry-ui:latest
    - name: Build and push Beta Debian Version
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./debian.dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.HUB_DOCKER_USERNAME }}/docker-registry-ui:${{ steps.vars.outputs.tag }}-debian
          registry.cn-hangzhou.aliyuncs.com/${{ secrets.HUB_DOCKER_USERNAME }}/docker-registry-ui:${{ steps.vars.outputs.tag }}-debian